//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessHelper.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessHelper.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calories (kcal): ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Calories_Title {
            get {
                return ResourceManager.GetString("MainMenu_Label_Calories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carbohydrates: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Carbohydrates_Title {
            get {
                return ResourceManager.GetString("MainMenu_Label_Carbohydrates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fats: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Fats_Title {
            get {
                return ResourceManager.GetString("MainMenu_Label_Fats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Month {
            get {
                return ResourceManager.GetString("MainMenu_Label_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protein: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Protein_Title {
            get {
                return ResourceManager.GetString("MainMenu_Label_Protein_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected Day: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_SelectedDay {
            get {
                return ResourceManager.GetString("MainMenu_Label_SelectedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meal: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Title_Meal {
            get {
                return ResourceManager.GetString("MainMenu_Label_Title_Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Week {
            get {
                return ResourceManager.GetString("MainMenu_Label_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yesterday: ähnelt.
        /// </summary>
        internal static string MainMenu_Label_Yesterday {
            get {
                return ResourceManager.GetString("MainMenu_Label_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview ähnelt.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        internal static string OptionsMenu_Button_AdministrateDays {
            get {
                return ResourceManager.GetString("OptionsMenu_Button_AdministrateDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nutrition/Meals ähnelt.
        /// </summary>
        internal static string OptionsMenu_Button_AdministrateFood {
            get {
                return ResourceManager.GetString("OptionsMenu_Button_AdministrateFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrate database ähnelt.
        /// </summary>
        internal static string OptionsMenu_GroupBox_GroupDatabaseAdministration {
            get {
                return ResourceManager.GetString("OptionsMenu_GroupBox_GroupDatabaseAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string OptionsMenu_GroupBox_LanguageSettings {
            get {
                return ResourceManager.GetString("OptionsMenu_GroupBox_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string OptionsMenuTitle {
            get {
                return ResourceManager.GetString("OptionsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fr ähnelt.
        /// </summary>
        internal static string Weekday_Friday {
            get {
                return ResourceManager.GetString("Weekday_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mo ähnelt.
        /// </summary>
        internal static string Weekday_Monday {
            get {
                return ResourceManager.GetString("Weekday_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sa ähnelt.
        /// </summary>
        internal static string Weekday_Saturday {
            get {
                return ResourceManager.GetString("Weekday_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Su ähnelt.
        /// </summary>
        internal static string Weekday_Sunday {
            get {
                return ResourceManager.GetString("Weekday_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Th ähnelt.
        /// </summary>
        internal static string Weekday_Thursday {
            get {
                return ResourceManager.GetString("Weekday_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tu ähnelt.
        /// </summary>
        internal static string Weekday_Tuesday {
            get {
                return ResourceManager.GetString("Weekday_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We ähnelt.
        /// </summary>
        internal static string Weekday_Wednesday {
            get {
                return ResourceManager.GetString("Weekday_Wednesday", resourceCulture);
            }
        }
    }
}
